/** Invertible book coordinate encoding.
 *
 * The target book's content is generated by a simple LCG whose initial state
 * encodes the book's coordinates. A player who reads the source can:
 *
 *   1. Read a few characters from any page of a book
 *   2. Recover the LCG state from consecutive outputs
 *   3. Reverse the state back to coordinates using the known seed
 *
 * The mapping is:
 *   coords → state:  state = mixCoords(coords) XOR seedKey
 *   state → coords:  coords = unmixCoords(state XOR seedKey)
 *
 * mixCoords/unmixCoords are a simple invertible bit-shuffle so that nearby
 * coordinates don't produce obviously similar output.
 *
 * The LCG is deliberately weak — that's the point. It's a puzzle, not crypto.
 *
 * @module invertible.core
 */

import { hash } from "./prng.core.js";

/* ---- Constants ---- */

const CHARSET_LEN = 95;
const CHARS_PER_LINE = 80;
const LINES_PER_PAGE = 40;

/** LCG parameters (mod 2^32). Multiplier from Numerical Recipes. */
const LCG_A = 1664525;
const LCG_C = 1013904223;

/* ---- Invertible coordinate encoding ---- */

/**
 * Pack coordinates into a single 64-bit-ish pair of 32-bit words.
 * Layout:
 *   word0: (side << 31) | ((floor & 0x7FFF) << 16) | (bookIndex & 0xFFFF)
 *   word1: position as signed int32 (reinterpreted as uint32)
 */
function packCoords(side, position, floor, bookIndex) {
    const w0 = ((side & 1) << 31) | ((floor & 0x7FFF) << 16) | (bookIndex & 0xFFFF);
    const w1 = position | 0; // signed → int32 bits
    return [w0 >>> 0, w1 >>> 0];
}

function unpackCoords(w0, w1) {
    const side = (w0 >>> 31) & 1;
    const floor = (w0 >>> 16) & 0x7FFF;
    const bookIndex = w0 & 0xFFFF;
    const position = w1 | 0; // reinterpret as signed
    return { side, position, floor, bookIndex };
}

/**
 * Invertible 32-bit mix (based on splitmix32 finalizer).
 * Each step is reversible.
 */
function mix32(x) {
    x = x >>> 0;
    x ^= x >>> 16;
    x = Math.imul(x, 0x45d9f3b);
    x ^= x >>> 16;
    x = Math.imul(x, 0x45d9f3b);
    x ^= x >>> 16;
    return x >>> 0;
}

/** Inverse of mix32. */
function unmix32(x) {
    x = x >>> 0;
    x ^= x >>> 16;
    x = Math.imul(x, 0x119de1f3); // modular inverse of 0x45d9f3b mod 2^32
    x ^= x >>> 16;
    x = Math.imul(x, 0x119de1f3);
    x ^= x >>> 16;
    return x >>> 0;
}

/**
 * Derive a 2-word key from the global seed string.
 * This is what the player needs to know (it's just hash(seed + suffix)).
 */
function seedKey(globalSeed) {
    return [hash(globalSeed + ":inv0"), hash(globalSeed + ":inv1")];
}

/**
 * Encode coordinates into a 2-word LCG state.
 *
 * coords → pack → mix each word → XOR with seed key
 *
 * @param {number} side
 * @param {number} position
 * @param {number} floor
 * @param {number} bookIndex
 * @param {string} globalSeed
 * @returns {[number, number]} two uint32 state words
 */
export function encodeCoords(side, position, floor, bookIndex, globalSeed) {
    const [w0, w1] = packCoords(side, position, floor, bookIndex);
    const [k0, k1] = seedKey(globalSeed);
    return [(mix32(w0) ^ k0) >>> 0, (mix32(w1) ^ k1) >>> 0];
}

/**
 * Decode a 2-word state back to coordinates.
 *
 * state → XOR with seed key → unmix each word → unpack
 *
 * @param {number} s0
 * @param {number} s1
 * @param {string} globalSeed
 * @returns {{ side, position, floor, bookIndex }}
 */
export function decodeCoords(s0, s1, globalSeed) {
    const [k0, k1] = seedKey(globalSeed);
    const w0 = unmix32((s0 ^ k0) >>> 0);
    const w1 = unmix32((s1 ^ k1) >>> 0);
    return unpackCoords(w0, w1);
}

/* ---- LCG ---- */

/** Advance LCG state by one step. */
function lcgNext(s) {
    return (Math.imul(LCG_A, s) + LCG_C) >>> 0;
}

/** Reverse LCG state by one step. */
// LCG_A_INV is the modular inverse of LCG_A mod 2^32.
const LCG_A_INV = 4276115653; // computed: LCG_A * LCG_A_INV ≡ 1 (mod 2^32)
export function lcgPrev(s) {
    return Math.imul((s - LCG_C) >>> 0, LCG_A_INV) >>> 0;
}

/**
 * Create an LCG stream from a 2-word state.
 * s0 is the running LCG state. s1 is mixed in once at the start via XOR,
 * giving 64 bits of effective key space while keeping a simple 32-bit LCG
 * that's easy to reverse from output.
 *
 * Two independent LCGs read in alternation: even chars from s0, odd from s1.
 */
function makeLCG(s0, s1) {
    let a = s0 >>> 0, b = s1 >>> 0;
    let even = true;
    return {
        nextInt(n) {
            if (even) {
                a = lcgNext(a);
                even = false;
                return a % n;
            } else {
                b = lcgNext(b);
                even = true;
                return b % n;
            }
        },
        state() { return [a, b]; }
    };
}

/* ---- Page generation ---- */

/**
 * Generate a page of a book using the invertible LCG.
 * The state is derived from coordinates + seed, and can be reversed.
 *
 * @param {number} side
 * @param {number} position
 * @param {number} floor
 * @param {number} bookIndex
 * @param {number} pageIndex - 0-based
 * @param {string} globalSeed
 * @returns {string}
 */
export function generateTargetPage(side, position, floor, bookIndex, pageIndex, globalSeed) {
    const [s0, s1] = encodeCoords(side, position, floor, bookIndex, globalSeed);

    // Advance LCG past prior pages to maintain determinism.
    const charsPerPage = LINES_PER_PAGE * CHARS_PER_LINE;
    const skipCalls = pageIndex * charsPerPage;
    const skipPerChain = Math.floor(skipCalls / 2);
    const extraEven = skipCalls % 2;

    let a = s0, b = s1;
    for (let i = 0; i < skipPerChain + extraEven; i++) a = lcgNext(a);
    for (let i = 0; i < skipPerChain; i++) b = lcgNext(b);

    const lcg = makeLCG(a, b);
    const lines = [];
    for (let l = 0; l < LINES_PER_PAGE; l++) {
        let line = "";
        for (let c = 0; c < CHARS_PER_LINE; c++) {
            line += String.fromCharCode(32 + lcg.nextInt(CHARSET_LEN));
        }
        lines.push(line);
    }
    return lines.join("\n");
}

/**
 * Recover coordinates from consecutive output characters of a book page.
 *
 * Requires at least 10 consecutive characters from the START of page 0.
 * (5 per chain → ~32.8 bits of constraint, uniquely pins each 32-bit state.)
 *
 * @param {string} chars - at least 10 characters from the beginning of page 0
 * @param {string} globalSeed
 * @returns {{ side, position, floor, bookIndex } | null}
 */
export function recoverCoords(chars, globalSeed) {
    if (chars.length < 10) return null;

    const v = [];
    for (let i = 0; i < chars.length && i < 12; i++) {
        v.push(chars.charCodeAt(i) - 32);
    }

    const evenTargets = [];
    for (let i = 0; i < v.length; i += 2) evenTargets.push(v[i]);

    const oddTargets = [];
    for (let i = 1; i < v.length; i += 2) oddTargets.push(v[i]);

    const foundS0 = recoverOneChain(evenTargets);
    if (foundS0 === null) return null;

    const foundS1 = recoverOneChain(oddTargets);
    if (foundS1 === null) return null;

    return decodeCoords(foundS0, foundS1, globalSeed);
}

/**
 * Recover the initial state of one LCG chain given consecutive outputs mod 95.
 * targets[0] = lcgNext(s) % 95, targets[1] = lcgNext^2(s) % 95, etc.
 * Returns s, or null if no match.
 */
function recoverOneChain(targets) {
    if (targets.length < 2) return null;

    for (let a = targets[0]; a < 0x100000000; a += CHARSET_LEN) {
        let match = true;
        let cur = a;
        for (let i = 1; i < targets.length; i++) {
            cur = lcgNext(cur);
            if (cur % CHARSET_LEN !== targets[i]) { match = false; break; }
        }
        if (match) return lcgPrev(a);
    }
    return null;
}

/* ---- Exports for solver/test use ---- */
export { LCG_A, LCG_C, LCG_A_INV, CHARSET_LEN };
export { packCoords, unpackCoords, mix32, unmix32, seedKey };
export { lcgNext, makeLCG };
